apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-service
  labels:
    app: bff-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-service
  template:
    metadata:
      labels:
        app: bff-service
    spec:
      containers:
      - name: bff-service
        image: bff-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: BFF_HTTP_PORT
          value: "8080"
        - name: TRANSACTION_SERVICE_ADDR
          value: "transaction-service:50051"
