[tools]
go = "1.25.5"
buf = "1.61.0"
grpcurl = "1.9.3"
kind = "0.26.0"
kubectl = "1.32.0"
helm = "3.16.3"
helmfile = "0.169.2"
"aqua:istio/istio/istioctl" = "1.24.2"
"go:github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway" = "v2.24.0"
