apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bff-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - foresee-gateway
  http:
  - match:
    - uri:
        prefix: /api/v1
    route:
    - destination:
        host: bff-service
        port:
          number: 8080
