type: google.api.Service
config_version: 3

http:
  rules:
    # Transaction Service - /api/v1/transactions/* 配下
    - selector: transaction.v1.TransactionService.HealthCheck
      get: /api/v1/transactions/health
